author: Darkeh
database: false
description: Completely new generators for the Overworld, the Nether, and Skylands
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: org.bytefire.plugins.shipwreckedwgen.ShipwreckedWGen
name: ShipGen
load: STARTUP
version: '0.8'
depends: 'org.bukkit.bukkit-1.6.2-R0.1'
